name: Build and deploy Company Communicator Web

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  SOLUTION: Source/Microsoft.Teams.Apps.CompanyCommunicator.sln
  WEB_PROJ: Source/CompanyCommunicator/CompanyCommunicator.csproj
  PUBLISH_DIR: ${{ github.workspace }}/publish_web

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      # Usa el SDK exacto que marca global.json (arregla el primer error del SDK)
      - name: Set up .NET from global.json
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Restore
        run: dotnet restore "${{ env.SOLUTION }}"

      - name: Build (Release)
        run: dotnet build "${{ env.SOLUTION }}" --configuration Release --no-restore

      # Publica SOLO el proyecto web para App Service
      - name: Publish Web
        run: dotnet publish "${{ env.WEB_PROJ }}" -c Release -o "${{ env.PUBLISH_DIR }}" --no-build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: webapp
          path: ${{ env.PUBLISH_DIR }}

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: webapp

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7EAFAA7D5B9A4E62AA80686B34BA6E04 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_18A36CF63F2F45A686A86C8D6948D57E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E3FF7B50D5D2442CBF5B84E562266A91 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'jmmcompcom'
          slot-name: 'Production'
          package: .
